# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("images/icons/16x16/bread.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabManager = QtGui.QTabWidget(self.centralwidget)
        self.tabManager.setGeometry(QtCore.QRect(10, 80, 781, 391))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.tabManager.setFont(font)
        self.tabManager.setObjectName(_fromUtf8("tabManager"))
        self.tabAccount = QtGui.QWidget()
        self.tabAccount.setObjectName(_fromUtf8("tabAccount"))
        self.frameLogin = QtGui.QFrame(self.tabAccount)
        self.frameLogin.setGeometry(QtCore.QRect(10, 10, 331, 341))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.frameLogin.setFont(font)
        self.frameLogin.setFrameShape(QtGui.QFrame.Box)
        self.frameLogin.setFrameShadow(QtGui.QFrame.Raised)
        self.frameLogin.setObjectName(_fromUtf8("frameLogin"))
        self.txtUsername = QtGui.QLineEdit(self.frameLogin)
        self.txtUsername.setGeometry(QtCore.QRect(100, 140, 211, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.txtUsername.setFont(font)
        self.txtUsername.setObjectName(_fromUtf8("txtUsername"))
        self.lblUsername = QtGui.QLabel(self.frameLogin)
        self.lblUsername.setGeometry(QtCore.QRect(10, 140, 81, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.lblUsername.setFont(font)
        self.lblUsername.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblUsername.setObjectName(_fromUtf8("lblUsername"))
        self.lblPassword = QtGui.QLabel(self.frameLogin)
        self.lblPassword.setGeometry(QtCore.QRect(20, 170, 71, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.lblPassword.setFont(font)
        self.lblPassword.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPassword.setObjectName(_fromUtf8("lblPassword"))
        self.txtPassword = QtGui.QLineEdit(self.frameLogin)
        self.txtPassword.setGeometry(QtCore.QRect(100, 170, 211, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.txtPassword.setFont(font)
        self.txtPassword.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.txtPassword.setObjectName(_fromUtf8("txtPassword"))
        self.btnLogin = QtGui.QCommandLinkButton(self.frameLogin)
        self.btnLogin.setGeometry(QtCore.QRect(230, 230, 81, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.btnLogin.setFont(font)
        self.btnLogin.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("images/icons/24x24/checkmark.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLogin.setIcon(icon1)
        self.btnLogin.setObjectName(_fromUtf8("btnLogin"))
        self.lblAccount = QtGui.QLabel(self.frameLogin)
        self.lblAccount.setGeometry(QtCore.QRect(10, 30, 91, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lblAccount.setFont(font)
        self.lblAccount.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblAccount.setObjectName(_fromUtf8("lblAccount"))
        self.comboAccounts = QtGui.QComboBox(self.frameLogin)
        self.comboAccounts.setGeometry(QtCore.QRect(10, 70, 221, 33))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.comboAccounts.setFont(font)
        self.comboAccounts.setObjectName(_fromUtf8("comboAccounts"))
        self.btnForget = QtGui.QPushButton(self.frameLogin)
        self.btnForget.setGeometry(QtCore.QRect(240, 70, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.btnForget.setFont(font)
        self.btnForget.setObjectName(_fromUtf8("btnForget"))
        self.checkboxRememberAccount = QtGui.QCheckBox(self.frameLogin)
        self.checkboxRememberAccount.setGeometry(QtCore.QRect(170, 200, 151, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.checkboxRememberAccount.setFont(font)
        self.checkboxRememberAccount.setObjectName(_fromUtf8("checkboxRememberAccount"))
        self.line = QtGui.QFrame(self.frameLogin)
        self.line.setGeometry(QtCore.QRect(10, 110, 291, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.line.setFont(font)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.imgLogin = QtGui.QLabel(self.frameLogin)
        self.imgLogin.setGeometry(QtCore.QRect(90, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.imgLogin.setFont(font)
        self.imgLogin.setText(_fromUtf8(""))
        self.imgLogin.setPixmap(QtGui.QPixmap(_fromUtf8("images/icons/128x128/password.png")))
        self.imgLogin.setScaledContents(True)
        self.imgLogin.setObjectName(_fromUtf8("imgLogin"))
        self.frameLogin_2 = QtGui.QFrame(self.tabAccount)
        self.frameLogin_2.setGeometry(QtCore.QRect(350, 10, 421, 341))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.frameLogin_2.setFont(font)
        self.frameLogin_2.setFrameShape(QtGui.QFrame.Box)
        self.frameLogin_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frameLogin_2.setObjectName(_fromUtf8("frameLogin_2"))
        self.listDetails = QtGui.QListWidget(self.frameLogin_2)
        self.listDetails.setGeometry(QtCore.QRect(10, 10, 401, 321))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.listDetails.setFont(font)
        self.listDetails.setFrameShape(QtGui.QFrame.Box)
        self.listDetails.setFrameShadow(QtGui.QFrame.Sunken)
        self.listDetails.setAlternatingRowColors(True)
        self.listDetails.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.listDetails.setObjectName(_fromUtf8("listDetails"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("images/icons/16x16/info.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabManager.addTab(self.tabAccount, icon2, _fromUtf8(""))
        self.tabRoutes = QtGui.QWidget()
        self.tabRoutes.setObjectName(_fromUtf8("tabRoutes"))
        self.treeRoutes = QtGui.QTreeWidget(self.tabRoutes)
        self.treeRoutes.setGeometry(QtCore.QRect(10, 10, 761, 341))
        self.treeRoutes.setObjectName(_fromUtf8("treeRoutes"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("images/icons/16x16/truck.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabManager.addTab(self.tabRoutes, icon3, _fromUtf8(""))
        self.tabOrderByDay = QtGui.QWidget()
        self.tabOrderByDay.setObjectName(_fromUtf8("tabOrderByDay"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("images/icons/16x16/calendar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabManager.addTab(self.tabOrderByDay, icon4, _fromUtf8(""))
        self.tabCustomers = QtGui.QWidget()
        self.tabCustomers.setObjectName(_fromUtf8("tabCustomers"))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("images/icons/16x16/customers.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabManager.addTab(self.tabCustomers, icon5, _fromUtf8(""))
        self.tabPrint = QtGui.QWidget()
        self.tabPrint.setObjectName(_fromUtf8("tabPrint"))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("images/icons/16x16/print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabManager.addTab(self.tabPrint, icon6, _fromUtf8(""))
        self.tabSettings = QtGui.QWidget()
        self.tabSettings.setObjectName(_fromUtf8("tabSettings"))
        self.frameLogin_3 = QtGui.QFrame(self.tabSettings)
        self.frameLogin_3.setGeometry(QtCore.QRect(140, 10, 631, 341))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.frameLogin_3.setFont(font)
        self.frameLogin_3.setFrameShape(QtGui.QFrame.Box)
        self.frameLogin_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frameLogin_3.setObjectName(_fromUtf8("frameLogin_3"))
        self.tableSettings = QtGui.QTableWidget(self.frameLogin_3)
        self.tableSettings.setGeometry(QtCore.QRect(10, 10, 611, 321))
        self.tableSettings.setAlternatingRowColors(True)
        self.tableSettings.setGridStyle(QtCore.Qt.DashLine)
        self.tableSettings.setColumnCount(2)
        self.tableSettings.setObjectName(_fromUtf8("tableSettings"))
        self.tableSettings.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableSettings.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableSettings.setHorizontalHeaderItem(1, item)
        self.tableSettings.horizontalHeader().setVisible(False)
        self.tableSettings.horizontalHeader().setHighlightSections(True)
        self.tableSettings.horizontalHeader().setSortIndicatorShown(True)
        self.tableSettings.horizontalHeader().setStretchLastSection(True)
        self.tableSettings.verticalHeader().setVisible(False)
        self.tableSettings.verticalHeader().setCascadingSectionResizes(False)
        self.tableSettings.verticalHeader().setHighlightSections(True)
        self.imgSettings = QtGui.QLabel(self.tabSettings)
        self.imgSettings.setGeometry(QtCore.QRect(20, 10, 101, 101))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.imgSettings.setFont(font)
        self.imgSettings.setText(_fromUtf8(""))
        self.imgSettings.setPixmap(QtGui.QPixmap(_fromUtf8("images/icons/128x128/settings.png")))
        self.imgSettings.setScaledContents(True)
        self.imgSettings.setObjectName(_fromUtf8("imgSettings"))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("images/icons/16x16/settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabManager.addTab(self.tabSettings, icon7, _fromUtf8(""))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 490, 781, 101))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.frame.setFont(font)
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.btnDownload = QtGui.QPushButton(self.frame)
        self.btnDownload.setGeometry(QtCore.QRect(110, 30, 51, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.btnDownload.setFont(font)
        self.btnDownload.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("images/icons/24x24/download.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDownload.setIcon(icon8)
        self.btnDownload.setObjectName(_fromUtf8("btnDownload"))
        self.imgLink = QtGui.QLabel(self.frame)
        self.imgLink.setGeometry(QtCore.QRect(80, 30, 21, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.imgLink.setFont(font)
        self.imgLink.setText(_fromUtf8(""))
        self.imgLink.setPixmap(QtGui.QPixmap(_fromUtf8("images/icons/128x128/link.png")))
        self.imgLink.setScaledContents(True)
        self.imgLink.setObjectName(_fromUtf8("imgLink"))
        self.listStatus = QtGui.QListWidget(self.frame)
        self.listStatus.setGeometry(QtCore.QRect(200, 10, 381, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.listStatus.setFont(font)
        self.listStatus.setFrameShape(QtGui.QFrame.Box)
        self.listStatus.setFrameShadow(QtGui.QFrame.Sunken)
        self.listStatus.setAlternatingRowColors(True)
        self.listStatus.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.listStatus.setObjectName(_fromUtf8("listStatus"))
        self.imgServer = QtGui.QLabel(self.frame)
        self.imgServer.setGeometry(QtCore.QRect(10, 20, 61, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.imgServer.setFont(font)
        self.imgServer.setText(_fromUtf8(""))
        self.imgServer.setPixmap(QtGui.QPixmap(_fromUtf8("images/icons/128x128/server.png")))
        self.imgServer.setScaledContents(True)
        self.imgServer.setObjectName(_fromUtf8("imgServer"))
        self.imgLink1 = QtGui.QLabel(self.frame)
        self.imgLink1.setGeometry(QtCore.QRect(170, 30, 21, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.imgLink1.setFont(font)
        self.imgLink1.setText(_fromUtf8(""))
        self.imgLink1.setPixmap(QtGui.QPixmap(_fromUtf8("images/icons/128x128/link.png")))
        self.imgLink1.setScaledContents(True)
        self.imgLink1.setObjectName(_fromUtf8("imgLink1"))
        self.btnUpload = QtGui.QPushButton(self.frame)
        self.btnUpload.setGeometry(QtCore.QRect(620, 30, 51, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.btnUpload.setFont(font)
        self.btnUpload.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnUpload.setAutoFillBackground(False)
        self.btnUpload.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("images/icons/24x24/upload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUpload.setIcon(icon9)
        self.btnUpload.setFlat(False)
        self.btnUpload.setObjectName(_fromUtf8("btnUpload"))
        self.imgLink2 = QtGui.QLabel(self.frame)
        self.imgLink2.setGeometry(QtCore.QRect(590, 30, 21, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.imgLink2.setFont(font)
        self.imgLink2.setText(_fromUtf8(""))
        self.imgLink2.setPixmap(QtGui.QPixmap(_fromUtf8("images/icons/128x128/link.png")))
        self.imgLink2.setScaledContents(True)
        self.imgLink2.setObjectName(_fromUtf8("imgLink2"))
        self.imgServer1 = QtGui.QLabel(self.frame)
        self.imgServer1.setGeometry(QtCore.QRect(710, 20, 61, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.imgServer1.setFont(font)
        self.imgServer1.setText(_fromUtf8(""))
        self.imgServer1.setPixmap(QtGui.QPixmap(_fromUtf8("images/icons/128x128/server.png")))
        self.imgServer1.setScaledContents(True)
        self.imgServer1.setObjectName(_fromUtf8("imgServer1"))
        self.imgLink3 = QtGui.QLabel(self.frame)
        self.imgLink3.setGeometry(QtCore.QRect(680, 30, 21, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.imgLink3.setFont(font)
        self.imgLink3.setText(_fromUtf8(""))
        self.imgLink3.setPixmap(QtGui.QPixmap(_fromUtf8("images/icons/128x128/link.png")))
        self.imgLink3.setScaledContents(True)
        self.imgLink3.setObjectName(_fromUtf8("imgLink3"))
        self.imgIcon = QtGui.QLabel(self.centralwidget)
        self.imgIcon.setGeometry(QtCore.QRect(710, 10, 81, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.imgIcon.setFont(font)
        self.imgIcon.setText(_fromUtf8(""))
        self.imgIcon.setPixmap(QtGui.QPixmap(_fromUtf8("images/icons/128x128/bread.png")))
        self.imgIcon.setScaledContents(True)
        self.imgIcon.setObjectName(_fromUtf8("imgIcon"))
        self.lblConnectionStatus = QtGui.QLabel(self.centralwidget)
        self.lblConnectionStatus.setGeometry(QtCore.QRect(700, 80, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.lblConnectionStatus.setFont(font)
        self.lblConnectionStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lblConnectionStatus.setObjectName(_fromUtf8("lblConnectionStatus"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 661, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(33)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabManager.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.lblUsername.setText(_translate("MainWindow", "Username:", None))
        self.lblPassword.setText(_translate("MainWindow", "Password:", None))
        self.btnLogin.setText(_translate("MainWindow", "Login", None))
        self.lblAccount.setText(_translate("MainWindow", "Account", None))
        self.btnForget.setText(_translate("MainWindow", "Forget", None))
        self.checkboxRememberAccount.setText(_translate("MainWindow", "Remember Account", None))
        self.tabManager.setTabText(self.tabManager.indexOf(self.tabAccount), _translate("MainWindow", "Account", None))
        self.treeRoutes.headerItem().setText(0, _translate("MainWindow", "Routes", None))
        self.tabManager.setTabText(self.tabManager.indexOf(self.tabRoutes), _translate("MainWindow", "Routes", None))
        self.tabManager.setTabText(self.tabManager.indexOf(self.tabOrderByDay), _translate("MainWindow", "Orders by Day", None))
        self.tabManager.setTabText(self.tabManager.indexOf(self.tabCustomers), _translate("MainWindow", "Customers", None))
        self.tabManager.setTabText(self.tabManager.indexOf(self.tabPrint), _translate("MainWindow", "Print", None))
        self.tableSettings.setSortingEnabled(True)
        item = self.tableSettings.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Setting", None))
        item = self.tableSettings.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value", None))
        self.tabManager.setTabText(self.tabManager.indexOf(self.tabSettings), _translate("MainWindow", "Settings", None))
        self.lblConnectionStatus.setText(_translate("MainWindow", "Not Connected", None))
        self.label.setText(_translate("MainWindow", "Bread Buddy", None))

